export interface LocationPoint {
  id?: string;
  lat: number;
  lon: number;
  label: string;
  title?: string;
  subtitle?: string;
  category?: 'metro' | 'college' | 'transit' | 'tech_park' | 'airport' | 'locality' | 'landmark';
}

export const MOCK_LOCATIONS: LocationPoint[] = [
  // --- Colleges & Universities ---
  {
    id: 'panimalar_ec',
    title: 'Panimalar Engineering College',
    subtitle: 'Bangalore Trunk Road, Poonamallee, Chennai',
    label: 'Panimalar Engineering College, Poonamallee',
    lat: 13.0494,
    lon: 80.0754,
    category: 'college',
  },
  {
    id: 'iit_madras',
    title: 'IIT Madras (Indian Institute of Technology)',
    subtitle: 'Sardar Patel Road, Adyar / Guindy, Chennai',
    label: 'IIT Madras, Adyar, Chennai',
    lat: 12.9915,
    lon: 80.2337,
    category: 'college',
  },
  {
    id: 'anna_univ',
    title: 'Anna University (CEG Campus)',
    subtitle: 'Sardar Patel Road, Guindy, Chennai',
    label: 'Anna University, Guindy, Chennai',
    lat: 13.0109,
    lon: 80.2354,
    category: 'college',
  },
  {
    id: 'ssn_college',
    title: 'SSN College of Engineering',
    subtitle: 'Old Mahabalipuram Road (OMR), Kalavakkam, Chennai',
    label: 'SSN College of Engineering, OMR, Chennai',
    lat: 12.7509,
    lon: 80.1973,
    category: 'college',
  },
  {
    id: 'rec_college',
    title: 'Rajalakshmi Engineering College (REC)',
    subtitle: 'National Highway 4, Thandalam, Chennai',
    label: 'Rajalakshmi Engineering College, Thandalam',
    lat: 13.0086,
    lon: 80.0034,
    category: 'college',
  },
  {
    id: 'svce_college',
    title: 'Sri Venkateswara College of Engineering (SVCE)',
    subtitle: 'Pennalur, Sriperumbudur, Tamil Nadu',
    label: 'SVCE, Sriperumbudur, Tamil Nadu',
    lat: 12.9866,
    lon: 79.9723,
    category: 'college',
  },
  {
    id: 'srm_ist',
    title: 'SRM Institute of Science and Technology',
    subtitle: 'GST Road, Kattankulathur, Chennai',
    label: 'SRM University, Kattankulathur, Chennai',
    lat: 12.8230,
    lon: 80.0451,
    category: 'college',
  },
  {
    id: 'vit_chennai',
    title: 'VIT Chennai Campus',
    subtitle: 'Vandalur-Kelambakkam Road, Chennai',
    label: 'VIT Chennai, Vandalur-Kelambakkam Road',
    lat: 12.8406,
    lon: 80.1534,
    category: 'college',
  },
  {
    id: 'loyola_college',
    title: 'Loyola College',
    subtitle: 'Sterling Road, Nungambakkam, Chennai',
    label: 'Loyola College, Nungambakkam, Chennai',
    lat: 13.0645,
    lon: 80.2335,
    category: 'college',
  },
  {
    id: 'psg_tech',
    title: 'PSG College of Technology',
    subtitle: 'Avinashi Road, Peelamedu, Coimbatore',
    label: 'PSG College of Technology, Coimbatore',
    lat: 11.0247,
    lon: 77.0028,
    category: 'college',
  },
  {
    id: 'cit_coimbatore',
    title: 'Coimbatore Institute of Technology (CIT)',
    subtitle: 'Civil Aerodrome Post, Peelamedu, Coimbatore',
    label: 'CIT, Peelamedu, Coimbatore',
    lat: 11.0284,
    lon: 77.0274,
    category: 'college',
  },

  // --- Metro Stations ---
  {
    id: 'metro_central',
    title: 'Chennai Central Metro (Puratchi Thalaivar Dr. MGR)',
    subtitle: 'Line 1 & 2 Inter-corridor Junction, Park Town, Chennai',
    label: 'Chennai Central Metro, Chennai',
    lat: 13.0814,
    lon: 80.2729,
    category: 'metro',
  },
  {
    id: 'metro_cmbt',
    title: 'CMBT Metro Station (Puratchi Thalaivi Dr. J. Jayalalithaa)',
    subtitle: 'Koyambedu Intermodal Hub, Chennai',
    label: 'CMBT Metro Station, Koyambedu, Chennai',
    lat: 13.0686,
    lon: 80.2039,
    category: 'metro',
  },
  {
    id: 'metro_guindy',
    title: 'Guindy Metro Station',
    subtitle: 'Anna Salai, Race Course, Guindy, Chennai',
    label: 'Guindy Metro Station, Chennai',
    lat: 13.0093,
    lon: 80.2131,
    category: 'metro',
  },
  {
    id: 'metro_airport',
    title: 'Chennai Airport Metro Station',
    subtitle: 'Terminal Link, GST Road, Meenambakkam, Chennai',
    label: 'Chennai Airport Metro, Meenambakkam',
    lat: 12.9808,
    lon: 80.1642,
    category: 'metro',
  },
  {
    id: 'metro_alandur',
    title: 'Arignar Anna Alandur Metro',
    subtitle: 'Interchange Station, GST Road, Alandur, Chennai',
    label: 'Alandur Metro Station, Chennai',
    lat: 13.0042,
    lon: 80.2015,
    category: 'metro',
  },
  {
    id: 'metro_vadapalani',
    title: 'Vadapalani Metro Station',
    subtitle: '100 Feet Road, Vadapalani Junction, Chennai',
    label: 'Vadapalani Metro Station, Chennai',
    lat: 13.0507,
    lon: 80.2121,
    category: 'metro',
  },
  {
    id: 'metro_annanagar_tower',
    title: 'Anna Nagar Tower Metro',
    subtitle: '2nd Avenue, Anna Nagar, Chennai',
    label: 'Anna Nagar Tower Metro, Chennai',
    lat: 13.0862,
    lon: 80.2120,
    category: 'metro',
  },
  {
    id: 'metro_thirumangalam',
    title: 'Thirumangalam Metro Station',
    subtitle: 'Jawaharlal Nehru Road, Thirumangalam, Chennai',
    label: 'Thirumangalam Metro, Chennai',
    lat: 13.0853,
    lon: 80.2016,
    category: 'metro',
  },
  {
    id: 'metro_egmore',
    title: 'Egmore Metro Station',
    subtitle: 'Gandhi Irwin Road, Egmore Railway Station, Chennai',
    label: 'Egmore Metro Station, Chennai',
    lat: 13.0791,
    lon: 80.2611,
    category: 'metro',
  },
  {
    id: 'metro_nandanam',
    title: 'Nandanam Metro Station',
    subtitle: 'Anna Salai / Venkatanarayana Road Junction, Chennai',
    label: 'Nandanam Metro Station, Chennai',
    lat: 13.0321,
    lon: 80.2423,
    category: 'metro',
  },

  // --- Major Transit Hubs & Terminals ---
  {
    id: 'hub_central_railway',
    title: 'Puratchi Thalaivar Dr. M.G. Ramachandran Central (MAS)',
    subtitle: 'EVR Periyar Salai, Park Town, Chennai',
    label: 'Chennai Central Railway Station, Chennai',
    lat: 13.0821,
    lon: 80.2756,
    category: 'transit',
  },
  {
    id: 'hub_egmore_railway',
    title: 'Chennai Egmore Railway Station (MS)',
    subtitle: 'Gandhi Irwin Road, Egmore, Chennai',
    label: 'Chennai Egmore Railway Station, Chennai',
    lat: 13.0784,
    lon: 80.2608,
    category: 'transit',
  },
  {
    id: 'hub_kilambakkam',
    title: 'Kalaignar Centenary Bus Terminus (KCBT)',
    subtitle: 'GST Road, Kilambakkam, Vandalur, Chennai',
    label: 'Kilambakkam Bus Terminus (KCBT), Chennai',
    lat: 12.8726,
    lon: 80.0821,
    category: 'transit',
  },
  {
    id: 'hub_koyambedu_bus',
    title: 'Koyambedu CMBT Bus Stand',
    subtitle: 'Inner Ring Road, Koyambedu, Chennai',
    label: 'Koyambedu CMBT Bus Stand, Chennai',
    lat: 13.0687,
    lon: 80.2051,
    category: 'transit',
  },
  {
    id: 'hub_chennai_airport',
    title: 'Chennai International Airport (MAA)',
    subtitle: 'GST Road, Meenambakkam, Chennai',
    label: 'Chennai International Airport (MAA)',
    lat: 12.9941,
    lon: 80.1709,
    category: 'airport',
  },
  {
    id: 'hub_tambaram',
    title: 'Tambaram Railway & Bus Terminus',
    subtitle: 'GST Road / Mudichur Road, Tambaram, Chennai',
    label: 'Tambaram Bus & Train Terminus, Chennai',
    lat: 12.9249,
    lon: 80.1200,
    category: 'transit',
  },
  {
    id: 'hub_poonamallee',
    title: 'Poonamallee Bus Terminus',
    subtitle: 'Trunk Road, Poonamallee, Chennai',
    label: 'Poonamallee Bus Terminus, Chennai',
    lat: 13.0517,
    lon: 80.0948,
    category: 'transit',
  },
  {
    id: 'hub_velachery_mrts',
    title: 'Velachery MRTS & Bus Hub',
    subtitle: 'Inner Ring Road, Velachery, Chennai',
    label: 'Velachery MRTS & Transit Hub, Chennai',
    lat: 12.9759,
    lon: 80.2212,
    category: 'transit',
  },
  {
    id: 'hub_gandhipuram',
    title: 'Gandhipuram Central Bus Stand',
    subtitle: 'Dr Nanjappa Road, Gandhipuram, Coimbatore',
    label: 'Gandhipuram Bus Stand, Coimbatore',
    lat: 11.0168,
    lon: 76.9686,
    category: 'transit',
  },

  // --- Tech Parks & Commercial Corridors ---
  {
    id: 'tech_tidel_park',
    title: 'Tidel Park Chennai',
    subtitle: 'Old Mahabalipuram Road (OMR), Tharamani, Chennai',
    label: 'Tidel Park, Tharamani, Chennai',
    lat: 12.9897,
    lon: 80.2483,
    category: 'tech_park',
  },
  {
    id: 'tech_dlf_porur',
    title: 'DLF Cybercity',
    subtitle: 'Mount Poonamallee Road, Manapakkam / Porur, Chennai',
    label: 'DLF Cybercity, Porur, Chennai',
    lat: 13.0232,
    lon: 80.1654,
    category: 'tech_park',
  },
  {
    id: 'tech_sipcot_siruseri',
    title: 'SIPCOT IT Park Siruseri',
    subtitle: 'OMR Corridor, Siruseri, Chennai',
    label: 'SIPCOT IT Park, Siruseri, Chennai',
    lat: 12.8282,
    lon: 80.2195,
    category: 'tech_park',
  },
  {
    id: 'tech_olympia',
    title: 'Olympia Tech Park',
    subtitle: 'SIDCO Industrial Estate, Guindy, Chennai',
    label: 'Olympia Tech Park, Guindy, Chennai',
    lat: 13.0118,
    lon: 80.2078,
    category: 'tech_park',
  },
  {
    id: 'tech_ascendas',
    title: 'Ascendas International Tech Park',
    subtitle: 'CSIR Road, Taramani, Chennai',
    label: 'Ascendas Tech Park, Taramani, Chennai',
    lat: 12.9863,
    lon: 80.2435,
    category: 'tech_park',
  },
  {
    id: 'tech_coimbatore_tidel',
    title: 'TIDEL Park Coimbatore',
    subtitle: 'ELCOT SEZ, Civil Aerodrome Post, Coimbatore',
    label: 'TIDEL Park Coimbatore',
    lat: 11.0287,
    lon: 77.0371,
    category: 'tech_park',
  },

  // --- Major Neighborhoods & Landmarks ---
  {
    id: 'loc_velachery',
    title: 'Velachery',
    subtitle: 'South Chennai residential & commercial hub',
    label: 'Velachery, Chennai',
    lat: 12.9759,
    lon: 80.2212,
    category: 'locality',
  },
  {
    id: 'loc_tnagar',
    title: 'T. Nagar (Thyagaraya Nagar)',
    subtitle: 'Panagal Park, Usman Road Shopping District, Chennai',
    label: 'T. Nagar, Chennai',
    lat: 13.0418,
    lon: 80.2341,
    category: 'locality',
  },
  {
    id: 'loc_annanagar',
    title: 'Anna Nagar West / Roundtana',
    subtitle: 'Shanti Colony, 2nd Avenue, Chennai',
    label: 'Anna Nagar, Chennai',
    lat: 13.0850,
    lon: 80.2101,
    category: 'locality',
  },
  {
    id: 'loc_adyar',
    title: 'Adyar',
    subtitle: 'L.B. Road, Adyar Bridge, South Chennai',
    label: 'Adyar, Chennai',
    lat: 13.0012,
    lon: 80.2565,
    category: 'locality',
  },
  {
    id: 'loc_nungambakkam',
    title: 'Nungambakkam',
    subtitle: 'Khader Nawaz Khan Road, College Road, Chennai',
    label: 'Nungambakkam, Chennai',
    lat: 13.0569,
    lon: 80.2425,
    category: 'locality',
  },
  {
    id: 'loc_mylapore',
    title: 'Mylapore',
    subtitle: 'Kapaleeshwarar Temple, Luz Church Road, Chennai',
    label: 'Mylapore, Chennai',
    lat: 13.0368,
    lon: 80.2676,
    category: 'locality',
  },
  {
    id: 'loc_besant_nagar',
    title: 'Besant Nagar (Elliot\'s Beach)',
    subtitle: 'Beach Road, 6th Avenue, Chennai',
    label: 'Besant Nagar, Chennai',
    lat: 13.0001,
    lon: 80.2667,
    category: 'landmark',
  },
  {
    id: 'loc_marina_beach',
    title: 'Marina Beach',
    subtitle: 'Kamarajar Promenade, Triplicane, Chennai',
    label: 'Marina Beach, Chennai',
    lat: 13.0500,
    lon: 80.2824,
    category: 'landmark',
  },
  {
    id: 'loc_porur',
    title: 'Porur Junction',
    subtitle: 'Mount Poonamallee Road, Chennai',
    label: 'Porur, Chennai',
    lat: 13.0382,
    lon: 80.1565,
    category: 'locality',
  },
  {
    id: 'loc_sholinganallur',
    title: 'Sholinganallur Junction',
    subtitle: 'OMR - ECR Link Road Junction, Chennai',
    label: 'Sholinganallur, OMR, Chennai',
    lat: 12.9010,
    lon: 80.2279,
    category: 'locality',
  },
  {
    id: 'loc_rs_puram',
    title: 'R.S. Puram',
    subtitle: 'DB Road, Coimbatore West',
    label: 'R.S. Puram, Coimbatore',
    lat: 11.0089,
    lon: 76.9509,
    category: 'locality',
  },
  {
    id: 'loc_peelamedu',
    title: 'Peelamedu',
    subtitle: 'Avinashi Road, Coimbatore East',
    label: 'Peelamedu, Coimbatore',
    lat: 11.0270,
    lon: 77.0125,
    category: 'locality',
  },
];
